exp: 
    exp_dir: experiments 
    device: cuda 
    seed: 777 
    use_wandb: True 
    model_type: diffusion 
    name: test 
    base_dir: /home/andrewut/genai_projects_task-main-2 
    key: null 
 
data: 
    name: base_dataset 
    input_train_dir: /home/andrewut/food_data/train
    input_val_dir: /home/andrewut/food_data/test
    train_batch_size: 64
    val_batch_size: 64
    workers: 8 
 
train: 
    trainer: base_diffusion_trainer 
    model: base_diffusion 
    optimizer: adam
    scheduler: onecycle 
    checkpoint_path: '/home/andrewut/genai_projects_task-main-2/saved_new/checkpoint_135000.pth' 
    val_metrics: ["fid"] 
    start_step: 0 
    steps: 300000 
    log_step: 1000
    checkpoint_step: 15000 
    val_step: 10000
 
 
model: 
    sample_size: 128
    in_channels: 3
    out_channels: 3
    layers_per_block: 2
    block_out_channels: [128, 128, 256, 256, 512, 512]
    down_block_types: ["DownBlock2D",  "DownBlock2D","DownBlock2D", "DownBlock2D", "AttnDownBlock2D", "DownBlock2D"]
    up_block_types: ["UpBlock2D", "AttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]
 
optimizer_args: 
    lr: 1e-7
    weight_decay: 1e-6
    betas: [0.95, 0.99]

scheduler_args:
    steps: 1000

 
lr_scheduler_args:
    name: cosine
    num_warmup_steps: 500
    num_training_steps: ${train.steps}
    # total_steps: ${train.steps}
    # max_lr: 1e-4
    # pct_start: 0.1
    # anneal_strategy: cos

losses_coef: 
    mse: 1.0 
 
logger: 
    project_name: "genai" 
    entity: null 
    run_name: "first_run" 
    mode: "online" 
    loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs) 
    log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B 
    id_length: 8 # length of the run_id 
 
to_save: 
    experiment_dir: /home/andrewut/genai_projects_task-main-2/saved_new_after_pretraining